repos:
  # Language agnostic formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        args:
          - --wrap=80
  - repo: https://github.com/instrumentl/pre-commit-just
    rev: v0.2
    hooks:
      - id: format-justfile

  # Shell
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.4.3
    hooks:
      - id: beautysh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck
        exclude: ^\.envrc$

  # Python
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.28.0
    hooks:
      - id: pyproject-fmt
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: ty
        name: ty
        entry: uv run ty check
        language: system
        types: [python]
        pass_filenames: false

  # Rust
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v2.1.4
    hooks:
      - id: cargo-sort
  - repo: local
    hooks:
      - id: cargo-machete
        name: cargo machete
        entry: bash -c 'cargo machete --fix'
        language: system
        pass_filenames: false
      - id: cargo-shear
        name: cargo shear
        entry: bash -c 'cargo shear --fix'
        language: system
        pass_filenames: false
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt'
        language: system
        pass_filenames: false
      - id: cargo-doc
        name: cargo doc
        entry: env CARGO_BUILD_WARNINGS=deny cargo doc
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: env CARGO_BUILD_WARNINGS=deny cargo clippy --all-targets --all-features
        language: system
        pass_filenames: false

  # Git
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: ./scripts/lint-commits.sh
        language: node
        additional_dependencies:
          - "@commitlint/cli@20.4.4"
        always_run: true
        pass_filenames: false
