[package]
name = "judicious"
version = "2026.10.1"
authors = ["Jonathan Gopel <jgopel@gmail.com>", "Tony Scimone <scimoneaj@gmail.com>"]
edition = "2024"
description = "A rate-limiting library that enforces a cooldown period after a resource has been used (return-time based)."
license-file = "LICENSE"
homepage = "https://github.com/jgopel/judicious"
repository = "https://github.com/jgopel/judicious"
readme = "README.md"
keywords = ["concurrency", "cooldown", "rate-limit"]
categories = ["asynchronous", "rust-patterns"]
include = ["/LICENSE", "/README.md", "src/**/*.rs"]

[workspace]
resolver = "3"
members = ["xtask"]
default-members = ["."]

[dependencies]
chrono = "0.4.45"
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["time"], optional = true }
tracing = "0.1.44"

[dev-dependencies]
pretty_assertions = "1.4.1"
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread", "time"] }

[features]
tokio = ["dep:tokio"]

[lints.clippy]
# Enable all warnings
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
restriction = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

# Blacklist some we don't agree with
absolute_paths = "allow"
arbitrary_source_item_ordering = "allow"
arithmetic_side_effects = "allow"
blanket_clippy_restriction_lints = "allow"
definition_in_module_root = "allow"
error_impl_error = "allow"
exhaustive_enums = "allow"
expect_used = "allow"
implicit_return = "allow"
inline_modules = "allow"
missing_assert_message = "allow"
missing_docs_in_private_items = "allow"
missing_inline_in_public_items = "allow"
mod_module_files = "allow"
question_mark_used = "allow"
single_call_fn = "allow"
single_char_lifetime_names = "allow"
std_instead_of_alloc = "allow"
std_instead_of_core = "allow"
use_debug = "allow"

[lints.rust]
missing_debug_implementations = "warn"
missing_docs = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unsafe_code = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1

[profile.perf]
inherits = "release"
debug = "full"
strip = "none"

[profile.release-with-asserts]
inherits = "release"
debug-assertions = true
