name: Quality

on:
  workflow_call:

env:
  CARGO_BUILD_WARNINGS: deny

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake check --no-update-lock-file
      - run: nix develop --ignore-env --command uv sync --locked

      - run: |
          nix develop \
            --ignore-env --keep-env-var BASE \
            --command just quality
        env:
          BASE: origin/main
      - run: |
          nix develop \
            --ignore-env --keep-env-var CARGO_BUILD_WARNINGS \
            --command just check-all-features
      - run: |
          nix develop \
            --ignore-env --keep-env-var CARGO_BUILD_WARNINGS \
            --command just udeps
