name: Test

on:
  workflow_call:

env:
  CARGO_BUILD_WARNINGS: deny

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: |
          nix develop \
            --ignore-env --keep-env-var CARGO_BUILD_WARNINGS \
            --command just test
